version: '2'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: jamiu
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autochek
    volumes:
       - ./data:/var/lib/postgresql
    ports:
      - 5432:5432
    container_name: postgres_db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: autochek@autochek.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 9090:80
    container_name: pgadmin
